/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 55
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 67
#define ALIAS_COUNT 0
#define TOKEN_COUNT 43
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_Format = 1,
  anon_sym_COLON = 2,
  anon_sym_FormatType = 3,
  anon_sym_EQ = 4,
  anon_sym_SCORE = 5,
  anon_sym_FRAMES = 6,
  anon_sym_MILLISECS = 7,
  anon_sym_SECS = 8,
  anon_sym_MINUTES = 9,
  anon_sym_SECS_AS_MINS = 10,
  anon_sym_VALUE = 11,
  anon_sym_UNSIGNED = 12,
  anon_sym_TENS = 13,
  anon_sym_HUNDREDS = 14,
  anon_sym_THOUSANDS = 15,
  anon_sym_FIXED1 = 16,
  anon_sym_FIXED2 = 17,
  anon_sym_FIXED3 = 18,
  anon_sym_FLOAT1 = 19,
  anon_sym_FLOAT2 = 20,
  anon_sym_FLOAT3 = 21,
  anon_sym_FLOAT4 = 22,
  anon_sym_FLOAT5 = 23,
  anon_sym_FLOAT6 = 24,
  anon_sym_Lookup = 25,
  anon_sym_COMMA = 26,
  anon_sym_DASH = 27,
  anon_sym_STAR = 28,
  aux_sym_number_token1 = 29,
  aux_sym_number_token2 = 30,
  sym_value = 31,
  anon_sym_Display = 32,
  anon_sym_LF = 33,
  anon_sym_QMARK = 34,
  anon_sym_AT = 35,
  anon_sym_LPAREN = 36,
  anon_sym_RPAREN = 37,
  sym_logic = 38,
  sym_text = 39,
  sym_default_display = 40,
  sym_identifier = 41,
  sym_comment = 42,
  sym_source_file = 43,
  sym__bloc = 44,
  sym_format = 45,
  sym_format_definition = 46,
  sym_format_type_definition = 47,
  sym_format_type = 48,
  sym_lookup = 49,
  sym_lookup_definition = 50,
  sym_lookup_statement = 51,
  sym_key = 52,
  sym_key_expr = 53,
  sym_key_item = 54,
  sym_range = 55,
  sym_number = 56,
  sym_display = 57,
  sym_display_header = 58,
  sym_conditional_display = 59,
  sym_condition = 60,
  sym_macro = 61,
  aux_sym_source_file_repeat1 = 62,
  aux_sym_lookup_repeat1 = 63,
  aux_sym_key_expr_repeat1 = 64,
  aux_sym_display_repeat1 = 65,
  aux_sym_conditional_display_repeat1 = 66,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_Format] = "Format",
  [anon_sym_COLON] = ":",
  [anon_sym_FormatType] = "FormatType",
  [anon_sym_EQ] = "=",
  [anon_sym_SCORE] = "SCORE",
  [anon_sym_FRAMES] = "FRAMES",
  [anon_sym_MILLISECS] = "MILLISECS",
  [anon_sym_SECS] = "SECS",
  [anon_sym_MINUTES] = "MINUTES",
  [anon_sym_SECS_AS_MINS] = "SECS_AS_MINS",
  [anon_sym_VALUE] = "VALUE",
  [anon_sym_UNSIGNED] = "UNSIGNED",
  [anon_sym_TENS] = "TENS",
  [anon_sym_HUNDREDS] = "HUNDREDS",
  [anon_sym_THOUSANDS] = "THOUSANDS",
  [anon_sym_FIXED1] = "FIXED1",
  [anon_sym_FIXED2] = "FIXED2",
  [anon_sym_FIXED3] = "FIXED3",
  [anon_sym_FLOAT1] = "FLOAT1",
  [anon_sym_FLOAT2] = "FLOAT2",
  [anon_sym_FLOAT3] = "FLOAT3",
  [anon_sym_FLOAT4] = "FLOAT4",
  [anon_sym_FLOAT5] = "FLOAT5",
  [anon_sym_FLOAT6] = "FLOAT6",
  [anon_sym_Lookup] = "Lookup",
  [anon_sym_COMMA] = ",",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [aux_sym_number_token1] = "number_token1",
  [aux_sym_number_token2] = "number_token2",
  [sym_value] = "value",
  [anon_sym_Display] = "Display",
  [anon_sym_LF] = "\n",
  [anon_sym_QMARK] = "\?",
  [anon_sym_AT] = "@",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_logic] = "logic",
  [sym_text] = "text",
  [sym_default_display] = "default_display",
  [sym_identifier] = "identifier",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__bloc] = "_bloc",
  [sym_format] = "format",
  [sym_format_definition] = "format_definition",
  [sym_format_type_definition] = "format_type_definition",
  [sym_format_type] = "format_type",
  [sym_lookup] = "lookup",
  [sym_lookup_definition] = "lookup_definition",
  [sym_lookup_statement] = "lookup_statement",
  [sym_key] = "key",
  [sym_key_expr] = "key_expr",
  [sym_key_item] = "key_item",
  [sym_range] = "range",
  [sym_number] = "number",
  [sym_display] = "display",
  [sym_display_header] = "display_header",
  [sym_conditional_display] = "conditional_display",
  [sym_condition] = "condition",
  [sym_macro] = "macro",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_lookup_repeat1] = "lookup_repeat1",
  [aux_sym_key_expr_repeat1] = "key_expr_repeat1",
  [aux_sym_display_repeat1] = "display_repeat1",
  [aux_sym_conditional_display_repeat1] = "conditional_display_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_Format] = anon_sym_Format,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_FormatType] = anon_sym_FormatType,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SCORE] = anon_sym_SCORE,
  [anon_sym_FRAMES] = anon_sym_FRAMES,
  [anon_sym_MILLISECS] = anon_sym_MILLISECS,
  [anon_sym_SECS] = anon_sym_SECS,
  [anon_sym_MINUTES] = anon_sym_MINUTES,
  [anon_sym_SECS_AS_MINS] = anon_sym_SECS_AS_MINS,
  [anon_sym_VALUE] = anon_sym_VALUE,
  [anon_sym_UNSIGNED] = anon_sym_UNSIGNED,
  [anon_sym_TENS] = anon_sym_TENS,
  [anon_sym_HUNDREDS] = anon_sym_HUNDREDS,
  [anon_sym_THOUSANDS] = anon_sym_THOUSANDS,
  [anon_sym_FIXED1] = anon_sym_FIXED1,
  [anon_sym_FIXED2] = anon_sym_FIXED2,
  [anon_sym_FIXED3] = anon_sym_FIXED3,
  [anon_sym_FLOAT1] = anon_sym_FLOAT1,
  [anon_sym_FLOAT2] = anon_sym_FLOAT2,
  [anon_sym_FLOAT3] = anon_sym_FLOAT3,
  [anon_sym_FLOAT4] = anon_sym_FLOAT4,
  [anon_sym_FLOAT5] = anon_sym_FLOAT5,
  [anon_sym_FLOAT6] = anon_sym_FLOAT6,
  [anon_sym_Lookup] = anon_sym_Lookup,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [aux_sym_number_token1] = aux_sym_number_token1,
  [aux_sym_number_token2] = aux_sym_number_token2,
  [sym_value] = sym_value,
  [anon_sym_Display] = anon_sym_Display,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_logic] = sym_logic,
  [sym_text] = sym_text,
  [sym_default_display] = sym_default_display,
  [sym_identifier] = sym_identifier,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__bloc] = sym__bloc,
  [sym_format] = sym_format,
  [sym_format_definition] = sym_format_definition,
  [sym_format_type_definition] = sym_format_type_definition,
  [sym_format_type] = sym_format_type,
  [sym_lookup] = sym_lookup,
  [sym_lookup_definition] = sym_lookup_definition,
  [sym_lookup_statement] = sym_lookup_statement,
  [sym_key] = sym_key,
  [sym_key_expr] = sym_key_expr,
  [sym_key_item] = sym_key_item,
  [sym_range] = sym_range,
  [sym_number] = sym_number,
  [sym_display] = sym_display,
  [sym_display_header] = sym_display_header,
  [sym_conditional_display] = sym_conditional_display,
  [sym_condition] = sym_condition,
  [sym_macro] = sym_macro,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_lookup_repeat1] = aux_sym_lookup_repeat1,
  [aux_sym_key_expr_repeat1] = aux_sym_key_expr_repeat1,
  [aux_sym_display_repeat1] = aux_sym_display_repeat1,
  [aux_sym_conditional_display_repeat1] = aux_sym_conditional_display_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_Format] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_FormatType] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SCORE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_FRAMES] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_MILLISECS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SECS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_MINUTES] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SECS_AS_MINS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_VALUE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_UNSIGNED] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TENS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_HUNDREDS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_THOUSANDS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_FIXED1] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_FIXED2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_FIXED3] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_FLOAT1] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_FLOAT2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_FLOAT3] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_FLOAT4] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_FLOAT5] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_FLOAT6] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Lookup] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_number_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_Display] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_logic] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_default_display] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__bloc] = {
    .visible = false,
    .named = true,
  },
  [sym_format] = {
    .visible = true,
    .named = true,
  },
  [sym_format_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_format_type_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_format_type] = {
    .visible = true,
    .named = true,
  },
  [sym_lookup] = {
    .visible = true,
    .named = true,
  },
  [sym_lookup_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_lookup_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_key] = {
    .visible = true,
    .named = true,
  },
  [sym_key_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_key_item] = {
    .visible = true,
    .named = true,
  },
  [sym_range] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_display] = {
    .visible = true,
    .named = true,
  },
  [sym_display_header] = {
    .visible = true,
    .named = true,
  },
  [sym_conditional_display] = {
    .visible = true,
    .named = true,
  },
  [sym_condition] = {
    .visible = true,
    .named = true,
  },
  [sym_macro] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_lookup_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_key_expr_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_display_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_conditional_display_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(100);
      ADVANCE_MAP(
        '(', 144,
        ')', 145,
        '*', 130,
        ',', 128,
        '-', 129,
        '/', 7,
        '0', 132,
        ':', 103,
        '=', 105,
        '?', 141,
        '@', 143,
        'D', 79,
        'F', 35,
        'H', 70,
        'L', 87,
        'M', 36,
        'S', 17,
        'T', 32,
        'U', 45,
        'V', 12,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(133);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(139);
      if (lookahead == '/') ADVANCE(151);
      if (lookahead == '@') ADVANCE(143);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(150);
      if (lookahead != 0) ADVANCE(153);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(140);
      if (lookahead == '/') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(3);
      if (lookahead == '/') ADVANCE(135);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(134);
      if (lookahead != 0) ADVANCE(136);
      END_STATE();
    case 4:
      if (lookahead == '\n') SKIP(4);
      if (lookahead == '/') ADVANCE(8);
      if (lookahead == '?') ADVANCE(141);
      if (lookahead == 'D') ADVANCE(80);
      if (lookahead == 'F') ADVANCE(85);
      if (lookahead == 'L') ADVANCE(86);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(5);
      if (lookahead != 0) ADVANCE(98);
      END_STATE();
    case 5:
      if (lookahead == '\n') SKIP(4);
      if (lookahead == '/') ADVANCE(154);
      if (lookahead == '?') ADVANCE(142);
      if (lookahead == 'D') ADVANCE(158);
      if (lookahead == 'F') ADVANCE(162);
      if (lookahead == 'L') ADVANCE(163);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(155);
      if (lookahead != 0) ADVANCE(172);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(173);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(174);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(172);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(172);
      END_STATE();
    case 9:
      if (lookahead == '/') ADVANCE(148);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(147);
      if (lookahead != 0 &&
          lookahead != ')' &&
          lookahead != '?') ADVANCE(149);
      END_STATE();
    case 10:
      if (lookahead == '1') ADVANCE(117);
      if (lookahead == '2') ADVANCE(118);
      if (lookahead == '3') ADVANCE(119);
      END_STATE();
    case 11:
      if (lookahead == '1') ADVANCE(120);
      if (lookahead == '2') ADVANCE(121);
      if (lookahead == '3') ADVANCE(122);
      if (lookahead == '4') ADVANCE(123);
      if (lookahead == '5') ADVANCE(124);
      if (lookahead == '6') ADVANCE(125);
      END_STATE();
    case 12:
      if (lookahead == 'A') ADVANCE(42);
      END_STATE();
    case 13:
      if (lookahead == 'A') ADVANCE(43);
      END_STATE();
    case 14:
      if (lookahead == 'A') ADVANCE(68);
      END_STATE();
    case 15:
      if (lookahead == 'A') ADVANCE(49);
      END_STATE();
    case 16:
      if (lookahead == 'A') ADVANCE(60);
      END_STATE();
    case 17:
      if (lookahead == 'C') ADVANCE(51);
      if (lookahead == 'E') ADVANCE(18);
      END_STATE();
    case 18:
      if (lookahead == 'C') ADVANCE(56);
      END_STATE();
    case 19:
      if (lookahead == 'C') ADVANCE(62);
      END_STATE();
    case 20:
      if (lookahead == 'D') ADVANCE(10);
      END_STATE();
    case 21:
      if (lookahead == 'D') ADVANCE(113);
      END_STATE();
    case 22:
      if (lookahead == 'D') ADVANCE(55);
      END_STATE();
    case 23:
      if (lookahead == 'D') ADVANCE(61);
      END_STATE();
    case 24:
      if (lookahead == 'D') ADVANCE(63);
      END_STATE();
    case 25:
      if (lookahead == 'E') ADVANCE(106);
      END_STATE();
    case 26:
      if (lookahead == 'E') ADVANCE(112);
      END_STATE();
    case 27:
      if (lookahead == 'E') ADVANCE(20);
      END_STATE();
    case 28:
      if (lookahead == 'E') ADVANCE(23);
      END_STATE();
    case 29:
      if (lookahead == 'E') ADVANCE(21);
      END_STATE();
    case 30:
      if (lookahead == 'E') ADVANCE(58);
      END_STATE();
    case 31:
      if (lookahead == 'E') ADVANCE(59);
      END_STATE();
    case 32:
      if (lookahead == 'E') ADVANCE(47);
      if (lookahead == 'H') ADVANCE(52);
      END_STATE();
    case 33:
      if (lookahead == 'E') ADVANCE(19);
      END_STATE();
    case 34:
      if (lookahead == 'G') ADVANCE(50);
      END_STATE();
    case 35:
      if (lookahead == 'I') ADVANCE(74);
      if (lookahead == 'L') ADVANCE(53);
      if (lookahead == 'R') ADVANCE(13);
      if (lookahead == 'o') ADVANCE(91);
      END_STATE();
    case 36:
      if (lookahead == 'I') ADVANCE(40);
      END_STATE();
    case 37:
      if (lookahead == 'I') ADVANCE(34);
      END_STATE();
    case 38:
      if (lookahead == 'I') ADVANCE(67);
      END_STATE();
    case 39:
      if (lookahead == 'I') ADVANCE(48);
      END_STATE();
    case 40:
      if (lookahead == 'L') ADVANCE(41);
      if (lookahead == 'N') ADVANCE(71);
      END_STATE();
    case 41:
      if (lookahead == 'L') ADVANCE(38);
      END_STATE();
    case 42:
      if (lookahead == 'L') ADVANCE(73);
      END_STATE();
    case 43:
      if (lookahead == 'M') ADVANCE(30);
      END_STATE();
    case 44:
      if (lookahead == 'M') ADVANCE(39);
      END_STATE();
    case 45:
      if (lookahead == 'N') ADVANCE(65);
      END_STATE();
    case 46:
      if (lookahead == 'N') ADVANCE(22);
      END_STATE();
    case 47:
      if (lookahead == 'N') ADVANCE(57);
      END_STATE();
    case 48:
      if (lookahead == 'N') ADVANCE(64);
      END_STATE();
    case 49:
      if (lookahead == 'N') ADVANCE(24);
      END_STATE();
    case 50:
      if (lookahead == 'N') ADVANCE(29);
      END_STATE();
    case 51:
      if (lookahead == 'O') ADVANCE(54);
      END_STATE();
    case 52:
      if (lookahead == 'O') ADVANCE(72);
      END_STATE();
    case 53:
      if (lookahead == 'O') ADVANCE(14);
      END_STATE();
    case 54:
      if (lookahead == 'R') ADVANCE(25);
      END_STATE();
    case 55:
      if (lookahead == 'R') ADVANCE(28);
      END_STATE();
    case 56:
      if (lookahead == 'S') ADVANCE(109);
      END_STATE();
    case 57:
      if (lookahead == 'S') ADVANCE(114);
      END_STATE();
    case 58:
      if (lookahead == 'S') ADVANCE(107);
      END_STATE();
    case 59:
      if (lookahead == 'S') ADVANCE(110);
      END_STATE();
    case 60:
      if (lookahead == 'S') ADVANCE(75);
      END_STATE();
    case 61:
      if (lookahead == 'S') ADVANCE(115);
      END_STATE();
    case 62:
      if (lookahead == 'S') ADVANCE(108);
      END_STATE();
    case 63:
      if (lookahead == 'S') ADVANCE(116);
      END_STATE();
    case 64:
      if (lookahead == 'S') ADVANCE(111);
      END_STATE();
    case 65:
      if (lookahead == 'S') ADVANCE(37);
      END_STATE();
    case 66:
      if (lookahead == 'S') ADVANCE(15);
      END_STATE();
    case 67:
      if (lookahead == 'S') ADVANCE(33);
      END_STATE();
    case 68:
      if (lookahead == 'T') ADVANCE(11);
      END_STATE();
    case 69:
      if (lookahead == 'T') ADVANCE(31);
      END_STATE();
    case 70:
      if (lookahead == 'U') ADVANCE(46);
      END_STATE();
    case 71:
      if (lookahead == 'U') ADVANCE(69);
      END_STATE();
    case 72:
      if (lookahead == 'U') ADVANCE(66);
      END_STATE();
    case 73:
      if (lookahead == 'U') ADVANCE(26);
      END_STATE();
    case 74:
      if (lookahead == 'X') ADVANCE(27);
      END_STATE();
    case 75:
      if (lookahead == '_') ADVANCE(44);
      END_STATE();
    case 76:
      if (lookahead == 'a') ADVANCE(93);
      END_STATE();
    case 77:
      if (lookahead == 'a') ADVANCE(95);
      END_STATE();
    case 78:
      if (lookahead == 'e') ADVANCE(104);
      END_STATE();
    case 79:
      if (lookahead == 'i') ADVANCE(92);
      END_STATE();
    case 80:
      if (lookahead == 'i') ADVANCE(168);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(172);
      END_STATE();
    case 81:
      if (lookahead == 'k') ADVANCE(94);
      END_STATE();
    case 82:
      if (lookahead == 'l') ADVANCE(77);
      END_STATE();
    case 83:
      if (lookahead == 'm') ADVANCE(76);
      END_STATE();
    case 84:
      if (lookahead == 'o') ADVANCE(81);
      END_STATE();
    case 85:
      if (lookahead == 'o') ADVANCE(167);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(172);
      END_STATE();
    case 86:
      if (lookahead == 'o') ADVANCE(164);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(172);
      END_STATE();
    case 87:
      if (lookahead == 'o') ADVANCE(84);
      END_STATE();
    case 88:
      if (lookahead == 'p') ADVANCE(82);
      END_STATE();
    case 89:
      if (lookahead == 'p') ADVANCE(126);
      END_STATE();
    case 90:
      if (lookahead == 'p') ADVANCE(78);
      END_STATE();
    case 91:
      if (lookahead == 'r') ADVANCE(83);
      END_STATE();
    case 92:
      if (lookahead == 's') ADVANCE(88);
      END_STATE();
    case 93:
      if (lookahead == 't') ADVANCE(101);
      END_STATE();
    case 94:
      if (lookahead == 'u') ADVANCE(89);
      END_STATE();
    case 95:
      if (lookahead == 'y') ADVANCE(137);
      END_STATE();
    case 96:
      if (lookahead == 'y') ADVANCE(90);
      END_STATE();
    case 97:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(131);
      END_STATE();
    case 98:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(172);
      END_STATE();
    case 99:
      if (eof) ADVANCE(100);
      if (lookahead == '\n') SKIP(99);
      if (lookahead == '/') ADVANCE(8);
      if (lookahead == '?') ADVANCE(141);
      if (lookahead == 'D') ADVANCE(80);
      if (lookahead == 'F') ADVANCE(85);
      if (lookahead == 'L') ADVANCE(86);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(5);
      if (lookahead != 0) ADVANCE(98);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_Format);
      if (lookahead == 'T') ADVANCE(96);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_Format);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(172);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_FormatType);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_SCORE);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_FRAMES);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_MILLISECS);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_SECS);
      if (lookahead == '_') ADVANCE(16);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_MINUTES);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_SECS_AS_MINS);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_VALUE);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(anon_sym_UNSIGNED);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(anon_sym_TENS);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(anon_sym_HUNDREDS);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_THOUSANDS);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(anon_sym_FIXED1);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(anon_sym_FIXED2);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(anon_sym_FIXED3);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(anon_sym_FLOAT1);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(anon_sym_FLOAT2);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(anon_sym_FLOAT3);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(anon_sym_FLOAT4);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(anon_sym_FLOAT5);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(anon_sym_FLOAT6);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(anon_sym_Lookup);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(anon_sym_Lookup);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(172);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(131);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(aux_sym_number_token2);
      if (lookahead == 'x') ADVANCE(97);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(133);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(aux_sym_number_token2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(133);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_value);
      if (lookahead == '/') ADVANCE(135);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(134);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(136);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_value);
      if (lookahead == '/') ADVANCE(136);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(136);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_value);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(136);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(anon_sym_Display);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(anon_sym_Display);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(172);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(139);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(150);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(140);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(anon_sym_QMARK);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(172);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(sym_logic);
      if (lookahead == '\n') ADVANCE(149);
      if (lookahead == ')' ||
          lookahead == '?') ADVANCE(174);
      if (lookahead != 0) ADVANCE(146);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(sym_logic);
      if (lookahead == '/') ADVANCE(148);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(147);
      if (lookahead != 0 &&
          lookahead != ')' &&
          lookahead != '?') ADVANCE(149);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(sym_logic);
      if (lookahead == '/') ADVANCE(146);
      if (lookahead != 0 &&
          lookahead != ')' &&
          lookahead != '?') ADVANCE(149);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(sym_logic);
      if (lookahead != 0 &&
          lookahead != ')' &&
          lookahead != '?') ADVANCE(149);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(139);
      if (lookahead == '/') ADVANCE(151);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(150);
      if (lookahead != 0 &&
          lookahead != '@') ADVANCE(153);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '/') ADVANCE(152);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(153);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '@') ADVANCE(174);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(152);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(153);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(sym_default_display);
      if (lookahead == '/') ADVANCE(172);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(172);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(sym_default_display);
      if (lookahead == '/') ADVANCE(154);
      if (lookahead == '?') ADVANCE(142);
      if (lookahead == 'D') ADVANCE(158);
      if (lookahead == 'F') ADVANCE(162);
      if (lookahead == 'L') ADVANCE(163);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(155);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(172);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(sym_default_display);
      if (lookahead == 'a') ADVANCE(169);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(172);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(sym_default_display);
      if (lookahead == 'a') ADVANCE(171);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(172);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(sym_default_display);
      if (lookahead == 'i') ADVANCE(168);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(172);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(sym_default_display);
      if (lookahead == 'k') ADVANCE(170);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(172);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(sym_default_display);
      if (lookahead == 'l') ADVANCE(157);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(172);
      END_STATE();
    case 161:
      ACCEPT_TOKEN(sym_default_display);
      if (lookahead == 'm') ADVANCE(156);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(172);
      END_STATE();
    case 162:
      ACCEPT_TOKEN(sym_default_display);
      if (lookahead == 'o') ADVANCE(167);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(172);
      END_STATE();
    case 163:
      ACCEPT_TOKEN(sym_default_display);
      if (lookahead == 'o') ADVANCE(164);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(172);
      END_STATE();
    case 164:
      ACCEPT_TOKEN(sym_default_display);
      if (lookahead == 'o') ADVANCE(159);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(172);
      END_STATE();
    case 165:
      ACCEPT_TOKEN(sym_default_display);
      if (lookahead == 'p') ADVANCE(160);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(172);
      END_STATE();
    case 166:
      ACCEPT_TOKEN(sym_default_display);
      if (lookahead == 'p') ADVANCE(127);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(172);
      END_STATE();
    case 167:
      ACCEPT_TOKEN(sym_default_display);
      if (lookahead == 'r') ADVANCE(161);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(172);
      END_STATE();
    case 168:
      ACCEPT_TOKEN(sym_default_display);
      if (lookahead == 's') ADVANCE(165);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(172);
      END_STATE();
    case 169:
      ACCEPT_TOKEN(sym_default_display);
      if (lookahead == 't') ADVANCE(102);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(172);
      END_STATE();
    case 170:
      ACCEPT_TOKEN(sym_default_display);
      if (lookahead == 'u') ADVANCE(166);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(172);
      END_STATE();
    case 171:
      ACCEPT_TOKEN(sym_default_display);
      if (lookahead == 'y') ADVANCE(138);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(172);
      END_STATE();
    case 172:
      ACCEPT_TOKEN(sym_default_display);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(172);
      END_STATE();
    case 173:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(173);
      END_STATE();
    case 174:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(174);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 99},
  [9] = {.lex_state = 99},
  [10] = {.lex_state = 99},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 99},
  [16] = {.lex_state = 99},
  [17] = {.lex_state = 99},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 6},
  [41] = {.lex_state = 9},
  [42] = {.lex_state = 6},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 6},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 3},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 9},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_Format] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_FormatType] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SCORE] = ACTIONS(1),
    [anon_sym_FRAMES] = ACTIONS(1),
    [anon_sym_MILLISECS] = ACTIONS(1),
    [anon_sym_SECS] = ACTIONS(1),
    [anon_sym_MINUTES] = ACTIONS(1),
    [anon_sym_SECS_AS_MINS] = ACTIONS(1),
    [anon_sym_VALUE] = ACTIONS(1),
    [anon_sym_UNSIGNED] = ACTIONS(1),
    [anon_sym_TENS] = ACTIONS(1),
    [anon_sym_HUNDREDS] = ACTIONS(1),
    [anon_sym_THOUSANDS] = ACTIONS(1),
    [anon_sym_FIXED1] = ACTIONS(1),
    [anon_sym_FIXED2] = ACTIONS(1),
    [anon_sym_FIXED3] = ACTIONS(1),
    [anon_sym_FLOAT1] = ACTIONS(1),
    [anon_sym_FLOAT2] = ACTIONS(1),
    [anon_sym_FLOAT3] = ACTIONS(1),
    [anon_sym_FLOAT4] = ACTIONS(1),
    [anon_sym_FLOAT5] = ACTIONS(1),
    [anon_sym_FLOAT6] = ACTIONS(1),
    [anon_sym_Lookup] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [aux_sym_number_token1] = ACTIONS(1),
    [aux_sym_number_token2] = ACTIONS(1),
    [anon_sym_Display] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(39),
    [sym__bloc] = STATE(7),
    [sym_format] = STATE(7),
    [sym_format_definition] = STATE(13),
    [sym_lookup] = STATE(7),
    [sym_lookup_definition] = STATE(3),
    [sym_display] = STATE(7),
    [sym_display_header] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_Format] = ACTIONS(7),
    [anon_sym_Lookup] = ACTIONS(9),
    [anon_sym_Display] = ACTIONS(11),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_SECS,
    STATE(26), 1,
      sym_format_type,
    ACTIONS(13), 19,
      anon_sym_SCORE,
      anon_sym_FRAMES,
      anon_sym_MILLISECS,
      anon_sym_MINUTES,
      anon_sym_SECS_AS_MINS,
      anon_sym_VALUE,
      anon_sym_UNSIGNED,
      anon_sym_TENS,
      anon_sym_HUNDREDS,
      anon_sym_THOUSANDS,
      anon_sym_FIXED1,
      anon_sym_FIXED2,
      anon_sym_FIXED3,
      anon_sym_FLOAT1,
      anon_sym_FLOAT2,
      anon_sym_FLOAT3,
      anon_sym_FLOAT4,
      anon_sym_FLOAT5,
      anon_sym_FLOAT6,
  [31] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      aux_sym_number_token2,
    STATE(28), 1,
      sym_number,
    STATE(33), 1,
      sym_key_item,
    STATE(37), 1,
      sym_range,
    STATE(43), 1,
      sym_key,
    STATE(46), 1,
      sym_key_expr,
    ACTIONS(19), 2,
      anon_sym_STAR,
      aux_sym_number_token1,
    STATE(4), 2,
      sym_lookup_statement,
      aux_sym_lookup_repeat1,
    ACTIONS(17), 4,
      ts_builtin_sym_end,
      anon_sym_Format,
      anon_sym_Lookup,
      anon_sym_Display,
  [67] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      aux_sym_number_token2,
    STATE(28), 1,
      sym_number,
    STATE(33), 1,
      sym_key_item,
    STATE(37), 1,
      sym_range,
    STATE(43), 1,
      sym_key,
    STATE(46), 1,
      sym_key_expr,
    ACTIONS(19), 2,
      anon_sym_STAR,
      aux_sym_number_token1,
    STATE(5), 2,
      sym_lookup_statement,
      aux_sym_lookup_repeat1,
    ACTIONS(23), 4,
      ts_builtin_sym_end,
      anon_sym_Format,
      anon_sym_Lookup,
      anon_sym_Display,
  [103] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(30), 1,
      aux_sym_number_token2,
    STATE(28), 1,
      sym_number,
    STATE(33), 1,
      sym_key_item,
    STATE(37), 1,
      sym_range,
    STATE(43), 1,
      sym_key,
    STATE(46), 1,
      sym_key_expr,
    ACTIONS(27), 2,
      anon_sym_STAR,
      aux_sym_number_token1,
    STATE(5), 2,
      sym_lookup_statement,
      aux_sym_lookup_repeat1,
    ACTIONS(25), 4,
      ts_builtin_sym_end,
      anon_sym_Format,
      anon_sym_Lookup,
      anon_sym_Display,
  [139] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    ACTIONS(35), 1,
      anon_sym_Format,
    ACTIONS(38), 1,
      anon_sym_Lookup,
    ACTIONS(41), 1,
      anon_sym_Display,
    STATE(3), 1,
      sym_lookup_definition,
    STATE(9), 1,
      sym_display_header,
    STATE(13), 1,
      sym_format_definition,
    STATE(6), 5,
      sym__bloc,
      sym_format,
      sym_lookup,
      sym_display,
      aux_sym_source_file_repeat1,
  [171] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_Format,
    ACTIONS(9), 1,
      anon_sym_Lookup,
    ACTIONS(11), 1,
      anon_sym_Display,
    ACTIONS(44), 1,
      ts_builtin_sym_end,
    STATE(3), 1,
      sym_lookup_definition,
    STATE(9), 1,
      sym_display_header,
    STATE(13), 1,
      sym_format_definition,
    STATE(6), 5,
      sym__bloc,
      sym_format,
      sym_lookup,
      sym_display,
      aux_sym_source_file_repeat1,
  [203] = 7,
    ACTIONS(46), 1,
      ts_builtin_sym_end,
    ACTIONS(50), 1,
      anon_sym_QMARK,
    ACTIONS(52), 1,
      sym_default_display,
    ACTIONS(54), 1,
      sym_comment,
    STATE(18), 1,
      sym_condition,
    STATE(10), 2,
      sym_conditional_display,
      aux_sym_display_repeat1,
    ACTIONS(48), 3,
      anon_sym_Format,
      anon_sym_Lookup,
      anon_sym_Display,
  [228] = 7,
    ACTIONS(50), 1,
      anon_sym_QMARK,
    ACTIONS(54), 1,
      sym_comment,
    ACTIONS(56), 1,
      ts_builtin_sym_end,
    ACTIONS(60), 1,
      sym_default_display,
    STATE(18), 1,
      sym_condition,
    STATE(8), 2,
      sym_conditional_display,
      aux_sym_display_repeat1,
    ACTIONS(58), 3,
      anon_sym_Format,
      anon_sym_Lookup,
      anon_sym_Display,
  [253] = 6,
    ACTIONS(54), 1,
      sym_comment,
    ACTIONS(62), 1,
      ts_builtin_sym_end,
    ACTIONS(66), 1,
      anon_sym_QMARK,
    STATE(18), 1,
      sym_condition,
    STATE(10), 2,
      sym_conditional_display,
      aux_sym_display_repeat1,
    ACTIONS(64), 4,
      anon_sym_Format,
      anon_sym_Lookup,
      anon_sym_Display,
      sym_default_display,
  [276] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 1,
      aux_sym_number_token2,
    ACTIONS(69), 6,
      ts_builtin_sym_end,
      anon_sym_Format,
      anon_sym_Lookup,
      anon_sym_STAR,
      aux_sym_number_token1,
      anon_sym_Display,
  [291] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      aux_sym_number_token2,
    ACTIONS(73), 6,
      ts_builtin_sym_end,
      anon_sym_Format,
      anon_sym_Lookup,
      anon_sym_STAR,
      aux_sym_number_token1,
      anon_sym_Display,
  [306] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      anon_sym_Format,
    ACTIONS(81), 1,
      anon_sym_FormatType,
    STATE(25), 1,
      sym_format_type_definition,
    ACTIONS(77), 3,
      ts_builtin_sym_end,
      anon_sym_Lookup,
      anon_sym_Display,
  [324] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      aux_sym_number_token2,
    STATE(28), 1,
      sym_number,
    STATE(36), 1,
      sym_key_item,
    STATE(37), 1,
      sym_range,
    ACTIONS(19), 2,
      anon_sym_STAR,
      aux_sym_number_token1,
  [344] = 3,
    ACTIONS(54), 1,
      sym_comment,
    ACTIONS(83), 1,
      ts_builtin_sym_end,
    ACTIONS(85), 5,
      anon_sym_Format,
      anon_sym_Lookup,
      anon_sym_Display,
      anon_sym_QMARK,
      sym_default_display,
  [358] = 3,
    ACTIONS(54), 1,
      sym_comment,
    ACTIONS(87), 1,
      ts_builtin_sym_end,
    ACTIONS(89), 5,
      anon_sym_Format,
      anon_sym_Lookup,
      anon_sym_Display,
      anon_sym_QMARK,
      sym_default_display,
  [372] = 3,
    ACTIONS(54), 1,
      sym_comment,
    ACTIONS(91), 1,
      ts_builtin_sym_end,
    ACTIONS(93), 5,
      anon_sym_Format,
      anon_sym_Lookup,
      anon_sym_Display,
      anon_sym_QMARK,
      sym_default_display,
  [386] = 5,
    ACTIONS(54), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym_LF,
    ACTIONS(97), 1,
      anon_sym_AT,
    ACTIONS(99), 1,
      sym_text,
    STATE(20), 2,
      sym_macro,
      aux_sym_conditional_display_repeat1,
  [403] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      anon_sym_Format,
    ACTIONS(101), 4,
      ts_builtin_sym_end,
      anon_sym_FormatType,
      anon_sym_Lookup,
      anon_sym_Display,
  [416] = 5,
    ACTIONS(54), 1,
      sym_comment,
    ACTIONS(97), 1,
      anon_sym_AT,
    ACTIONS(105), 1,
      anon_sym_LF,
    ACTIONS(107), 1,
      sym_text,
    STATE(21), 2,
      sym_macro,
      aux_sym_conditional_display_repeat1,
  [433] = 5,
    ACTIONS(54), 1,
      sym_comment,
    ACTIONS(109), 1,
      anon_sym_LF,
    ACTIONS(111), 1,
      anon_sym_AT,
    ACTIONS(114), 1,
      sym_text,
    STATE(21), 2,
      sym_macro,
      aux_sym_conditional_display_repeat1,
  [450] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 4,
      ts_builtin_sym_end,
      anon_sym_Format,
      anon_sym_Lookup,
      anon_sym_Display,
  [460] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      aux_sym_number_token2,
    STATE(35), 1,
      sym_number,
    ACTIONS(19), 2,
      anon_sym_STAR,
      aux_sym_number_token1,
  [474] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 4,
      ts_builtin_sym_end,
      anon_sym_Format,
      anon_sym_Lookup,
      anon_sym_Display,
  [484] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 4,
      ts_builtin_sym_end,
      anon_sym_Format,
      anon_sym_Lookup,
      anon_sym_Display,
  [494] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 4,
      ts_builtin_sym_end,
      anon_sym_Format,
      anon_sym_Lookup,
      anon_sym_Display,
  [504] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 4,
      ts_builtin_sym_end,
      anon_sym_Format,
      anon_sym_Lookup,
      anon_sym_Display,
  [514] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      anon_sym_DASH,
    ACTIONS(125), 2,
      anon_sym_EQ,
      anon_sym_COMMA,
  [525] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      anon_sym_EQ,
    ACTIONS(131), 1,
      anon_sym_COMMA,
    STATE(31), 1,
      aux_sym_key_expr_repeat1,
  [538] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 3,
      anon_sym_EQ,
      anon_sym_COMMA,
      anon_sym_DASH,
  [547] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      anon_sym_EQ,
    ACTIONS(137), 1,
      anon_sym_COMMA,
    STATE(31), 1,
      aux_sym_key_expr_repeat1,
  [560] = 2,
    ACTIONS(54), 1,
      sym_comment,
    ACTIONS(140), 3,
      anon_sym_LF,
      anon_sym_AT,
      sym_text,
  [569] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      anon_sym_COMMA,
    ACTIONS(142), 1,
      anon_sym_EQ,
    STATE(29), 1,
      aux_sym_key_expr_repeat1,
  [582] = 2,
    ACTIONS(54), 1,
      sym_comment,
    ACTIONS(144), 3,
      anon_sym_LF,
      anon_sym_AT,
      sym_text,
  [591] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 2,
      anon_sym_EQ,
      anon_sym_COMMA,
  [599] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 2,
      anon_sym_EQ,
      anon_sym_COMMA,
  [607] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 2,
      anon_sym_EQ,
      anon_sym_COMMA,
  [615] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 1,
      anon_sym_QMARK,
  [622] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 1,
      ts_builtin_sym_end,
  [629] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      sym_identifier,
  [636] = 2,
    ACTIONS(54), 1,
      sym_comment,
    ACTIONS(154), 1,
      sym_logic,
  [643] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 1,
      sym_identifier,
  [650] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 1,
      anon_sym_EQ,
  [657] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 1,
      sym_identifier,
  [664] = 2,
    ACTIONS(54), 1,
      sym_comment,
    ACTIONS(162), 1,
      anon_sym_LF,
  [671] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 1,
      anon_sym_EQ,
  [678] = 2,
    ACTIONS(54), 1,
      sym_comment,
    ACTIONS(166), 1,
      sym_value,
  [685] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 1,
      anon_sym_EQ,
  [692] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(170), 1,
      anon_sym_LPAREN,
  [699] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 1,
      anon_sym_COLON,
  [706] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 1,
      anon_sym_COLON,
  [713] = 2,
    ACTIONS(54), 1,
      sym_comment,
    ACTIONS(176), 1,
      sym_logic,
  [720] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 1,
      anon_sym_RPAREN,
  [727] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 31,
  [SMALL_STATE(4)] = 67,
  [SMALL_STATE(5)] = 103,
  [SMALL_STATE(6)] = 139,
  [SMALL_STATE(7)] = 171,
  [SMALL_STATE(8)] = 203,
  [SMALL_STATE(9)] = 228,
  [SMALL_STATE(10)] = 253,
  [SMALL_STATE(11)] = 276,
  [SMALL_STATE(12)] = 291,
  [SMALL_STATE(13)] = 306,
  [SMALL_STATE(14)] = 324,
  [SMALL_STATE(15)] = 344,
  [SMALL_STATE(16)] = 358,
  [SMALL_STATE(17)] = 372,
  [SMALL_STATE(18)] = 386,
  [SMALL_STATE(19)] = 403,
  [SMALL_STATE(20)] = 416,
  [SMALL_STATE(21)] = 433,
  [SMALL_STATE(22)] = 450,
  [SMALL_STATE(23)] = 460,
  [SMALL_STATE(24)] = 474,
  [SMALL_STATE(25)] = 484,
  [SMALL_STATE(26)] = 494,
  [SMALL_STATE(27)] = 504,
  [SMALL_STATE(28)] = 514,
  [SMALL_STATE(29)] = 525,
  [SMALL_STATE(30)] = 538,
  [SMALL_STATE(31)] = 547,
  [SMALL_STATE(32)] = 560,
  [SMALL_STATE(33)] = 569,
  [SMALL_STATE(34)] = 582,
  [SMALL_STATE(35)] = 591,
  [SMALL_STATE(36)] = 599,
  [SMALL_STATE(37)] = 607,
  [SMALL_STATE(38)] = 615,
  [SMALL_STATE(39)] = 622,
  [SMALL_STATE(40)] = 629,
  [SMALL_STATE(41)] = 636,
  [SMALL_STATE(42)] = 643,
  [SMALL_STATE(43)] = 650,
  [SMALL_STATE(44)] = 657,
  [SMALL_STATE(45)] = 664,
  [SMALL_STATE(46)] = 671,
  [SMALL_STATE(47)] = 678,
  [SMALL_STATE(48)] = 685,
  [SMALL_STATE(49)] = 692,
  [SMALL_STATE(50)] = 699,
  [SMALL_STATE(51)] = 706,
  [SMALL_STATE(52)] = 713,
  [SMALL_STATE(53)] = 720,
  [SMALL_STATE(54)] = 727,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lookup, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lookup, 2, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_lookup_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_lookup_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_lookup_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_display, 2, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_display, 2, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_display, 1, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_display, 1, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_display_repeat1, 2, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_display_repeat1, 2, 0, 0),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_display_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lookup_definition, 3, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lookup_definition, 3, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lookup_statement, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lookup_statement, 3, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_format, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conditional_display, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_conditional_display, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_display_header, 3, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_display_header, 3, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conditional_display, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_conditional_display, 3, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_definition, 3, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_format_definition, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_conditional_display_repeat1, 2, 0, 0),
  [111] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_conditional_display_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [114] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_conditional_display_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_display, 3, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 2, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_type_definition, 3, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_type, 1, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key_item, 1, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key_expr, 2, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_key_expr_repeat1, 2, 0, 0),
  [137] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_key_expr_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_condition, 3, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key_expr, 1, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro, 5, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_range, 3, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [150] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [154] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key, 1, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [176] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_rapresence(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "rapresence",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
